# Generated by Django 4.2.3 on 2023-07-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_imageupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='upload_image',
            new_name='image',
        ),
    ]
